version: '3'
services:
  bespin-database:
    image: postgres:9.5
    volumes:
      - db-data:/var/lib/postgresql/data
    # Setting vars in the database env file causes the postgres image to createdb and createrole
    env_file: bespin-database.env
    networks:
      - bespin-web
  bespin-web:
    depends_on:
      - bespin-database
    image: dukegcb/bespin-web
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - bespin-web.env
      - bespin-database.env # Since the web app needs database credentials
    volumes:
      - ./certs:/etc/external/ssl
      # - TODO: Add a volume for the bespin-ui
    networks:
      - bespin-web
volumes:
  db-data:
networks:
  bespin-web:
